stages:
    - genKey
    - build
    - deploy

variables:
    NODE_VERSION: "21"

before_script:
    # This will run before each job in all stages
    - echo "Setting up environment"
    - whoami

genKey:
    stage: genKey
    script:
        - echo "Creating key.pem file from environment variable"
        - echo "$AUTH_KEY" > key.pem
        - chmod 400 key.pem
    artifacts:
        paths:
        - key.pem  # Save key.pem as artifact for next stage
    only:
        - main

Nginx_Check:
    stage: genKey
    needs: ["genKey"]
    dependencies:
        - genKey
    script:
        - ssh -o StrictHostKeyChecking=no -i key.pem -A $INSTANCE@$INSTANCEADD '
            sudo nginx -t &&
            sudo systemctl disable nginx &&
            sudo systemctl enable nginx &&
            sudo systemctl restart nginx &&
            sudo systemctl status nginx'
    only:
        - main

build:
    stage: build
    cache:
        paths:
            - node_modules/  # Cache node_modules for future runs
    script:
        - echo "Installing node modules"
        - npm install
        - echo "Building application"
        - npm run build
    artifacts:
        paths:
        - dist/*  # Save dist directory as artifact for next stages
    only:
        - main

EnsuringDist:
    stage: deploy
    script:
        - echo "Cleaning up the dist directory on the instance"
        - ssh -o StrictHostKeyChecking=no -i key.pem -A $INSTANCE@$INSTANCEADD 'rm -rf /home/$ROOT/dist/'
    only:
        - main

Deploy:
    stage: deploy
    needs: ["build", "genKey", "EnsuringDist"]
    dependencies:
        - build
        - genKey
    script:
        - echo "Deploying build to instance"
        - ssh -o StrictHostKeyChecking=no -i key.pem -A $INSTANCE@$INSTANCEADD 'ls'
        - scp -o StrictHostKeyChecking=no -i key.pem -r dist/ $INSTANCE@$INSTANCEADD:/home/$ROOT/
    only:
        - main

EnsuringNginx:
    stage: deploy
    needs: ["Deploy", "genKey"]
    dependencies:
        - genKey
    script:
        - echo "Restarting NGINX service"
        - ssh -o StrictHostKeyChecking=no -i key.pem -A $INSTANCE@$INSTANCEADD '
            sudo systemctl restart nginx &&
            sudo systemctl status nginx &&
            echo "NGINX restarted successfully"'
    only:
        - main
